# Generated by Django 3.2.11 on 2022-02-14 23:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ansade_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.PositiveBigIntegerField(help_text='Annee de l execution', validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2050)], verbose_name='Annee')),
                ('lib_chap', models.CharField(blank=True, help_text='lib de chapitre', max_length=1000, null=True, verbose_name='Nom')),
                ('Libellé_SSCHAP', models.CharField(blank=True, help_text='lib de sous chapitre', max_length=1000, null=True, verbose_name='Nom')),
                ('C_PART', models.PositiveBigIntegerField(verbose_name='C_PART')),
                ('C_ART', models.PositiveBigIntegerField(verbose_name='C_ART')),
                ('C_PGPH', models.PositiveBigIntegerField(verbose_name='C_PGPH')),
                ('DOTATION', models.PositiveBigIntegerField(verbose_name='DOTATION')),
                ('INDISPONIBLE', models.PositiveBigIntegerField(verbose_name='INDISPONIBLE')),
                ('Indisp', models.PositiveBigIntegerField(verbose_name='Indisp')),
                ('DISPONIBLE', models.PositiveBigIntegerField(verbose_name='DISPONIBLE')),
                ('LIBELLE', models.CharField(blank=True, help_text='lib de sous chapitre', max_length=1000, null=True, verbose_name='lib_operation')),
            ],
        ),
        migrations.CreateModel(
            name='classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lib_chap', models.CharField(blank=True, help_text='lib de chapitre', max_length=1000, null=True, verbose_name='Nom')),
                ('LIBELLE', models.CharField(blank=True, help_text='lib de sous chapitre', max_length=1000, null=True, verbose_name='lib_operation')),
                ('Epi_Epac', models.CharField(help_text='EPI/EPAC', max_length=50, verbose_name='EPI/EPAC')),
                ('Branche', models.CharField(help_text='BRANCHE', max_length=50, verbose_name='BRANCHE')),
                ('Secteur', models.CharField(help_text='SECTEUR', max_length=50, verbose_name='SECTEUR')),
                ('Si', models.CharField(help_text='SI', max_length=50, verbose_name='SI')),
                ('Operation', models.CharField(help_text='PRODUIT', max_length=50, verbose_name='PRODUIT')),
            ],
        ),
    ]
