# Generated by Django 3.2.11 on 2022-02-14 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ansade_db',
            new_name='Ansad_db',
        ),
    ]
